Feed HLS and MP4 url to videojs
oszuidwest/streekomroep pull request #21
Opened 2021-11-02 15:47 UTC by rmens

This improves compatibility with certain android devices that don't support hls. Also it makes Chromecast work.

2021-11-02 15:56 UTC, rmens commented
@marijnvdwerf on old episodes where there is no HD mp4, the site falls back to the Vimeo player. We probably need a bit of 'pick the best quality mp4' logic here. Based on the `type` == `video/mp4` and `width` is highest. Can you take a look at expanding my first try?

```
 "files": [
    {
      "quality": "sd",
      "type": "video/mp4",
      "width": 426,
      "height": 240,
      "link": "xxxx",
      "created_time": "2021-11-01T17:33:45+00:00",
      "fps": 25,
      "size": 112815249,
      "md5": "75aabfa96a423688dd7bfc9739f7924a",
      "public_name": "SD 240p",
      "size_short": "107.59MB"
```

2021-11-05 15:47 UTC, marijnvdwerf requested changes

2021-11-05 15:47 UTC, marijnvdwerf commented on functions.php
> +        }
```php
        if ($source->type !== "video/mp4") continue;

        if (!$mp4 || $source->width > $mp4->width) {
            $mp4 = $source;
        }
```

2021-11-05 19:10 UTC, marijnvdwerf commented on functions.php
> +    $mp4 = null;
`var_dump($body->files); die()`?

2021-11-06 23:34 UTC, marijnvdwerf commented on functions.php
> +
(add)
```php
if (!isset($mp4->width)) {
    $mp4->width = 0;
}

2021-11-07 11:26 UTC, rmens commented
All edge cases handled. No more errors when running with `wp_debug` enabled. Think we are good to merge.

2021-11-07 12:20 UTC, marijnvdwerf approved these changes
Indenting is a bit weird, but should be functional like this

2021-11-07 12:30 UTC, merged